In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
ds=pd.read_csv('housing.csv')

In [3]:
ds

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [4]:
ds.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [5]:
median=ds['total_bedrooms'].median()

In [6]:
median

435.0

In [7]:
ds['total_bedrooms'].fillna(median,inplace=True)

In [8]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20640 non-null float64
latitude              20640 non-null float64
housing_median_age    20640 non-null float64
total_rooms           20640 non-null float64
total_bedrooms        20640 non-null float64
population            20640 non-null float64
households            20640 non-null float64
median_income         20640 non-null float64
median_house_value    20640 non-null float64
ocean_proximity       20640 non-null object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [9]:
ds

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le=LabelEncoder()

In [12]:
ds['ocean_proximity']=le.fit_transform(ds['ocean_proximity'])

In [13]:
ds

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

       ocean_proximity  
0                    3  
1                    3  
2                    3  
3                    3  
4                    3  
...                ...  
20635                1  
20636                1  
20637                1  
20638                1  
20639                1  

[20640 rows x 10 columns]

In [14]:
x_new=ds.drop(['median_house_value'],axis=1)

In [15]:
x_new

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  ocean_proximity  
0           322.0       126.0         8.3252                3  
1          2401.0      1138.0         8.3014                3  
2           496.0       177.0         7.2574                3  
3           558.0       219.0         5.6431                3  
4           565.0       259.0         3.8462                3  
...           ...         ...            ...              ...  
20635       845.0       330.0         1.5603                1  
20636       356.0       114.0         2.5568                1  
20637      1007.0       433.0         1.7000                1  
20638       741.0       349.0         1.8672                1  
20639      1387.0       530.0         2.3886                1  

[20640 rows x 9 columns]

In [16]:
x=x_new.iloc[:,1:9].values

In [17]:
x

array([[3.7880e+01, 4.1000e+01, 8.8000e+02, ..., 1.2600e+02, 8.3252e+00,
        3.0000e+00],
       [3.7860e+01, 2.1000e+01, 7.0990e+03, ..., 1.1380e+03, 8.3014e+00,
        3.0000e+00],
       [3.7850e+01, 5.2000e+01, 1.4670e+03, ..., 1.7700e+02, 7.2574e+00,
        3.0000e+00],
       ...,
       [3.9430e+01, 1.7000e+01, 2.2540e+03, ..., 4.3300e+02, 1.7000e+00,
        1.0000e+00],
       [3.9430e+01, 1.8000e+01, 1.8600e+03, ..., 3.4900e+02, 1.8672e+00,
        1.0000e+00],
       [3.9370e+01, 1.6000e+01, 2.7850e+03, ..., 5.3000e+02, 2.3886e+00,
        1.0000e+00]])

In [18]:
y=ds.iloc[:,8:9].values

In [19]:
y

array([[452600.],
       [358500.],
       [352100.],
       ...,
       [ 92300.],
       [ 84700.],
       [ 89400.]])

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [22]:
x_train

array([[3.3830e+01, 6.0000e+00, 5.0200e+02, ..., 6.5000e+01, 4.2386e+00,
        1.0000e+00],
       [3.7730e+01, 5.2000e+01, 2.3810e+03, ..., 4.4700e+02, 4.3898e+00,
        3.0000e+00],
       [3.3830e+01, 2.6000e+01, 1.7180e+03, ..., 3.6800e+02, 3.9333e+00,
        0.0000e+00],
       ...,
       [3.6580e+01, 3.1000e+01, 1.4310e+03, ..., 3.9300e+02, 3.1977e+00,
        4.0000e+00],
       [3.3620e+01, 3.4000e+01, 2.1250e+03, ..., 4.6800e+02, 5.6315e+00,
        0.0000e+00],
       [3.2800e+01, 1.5000e+01, 1.1710e+03, ..., 2.9800e+02, 1.3882e+00,
        1.0000e+00]])

In [ ]:
# MULTI LINEAR REGRESSION

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
lr=LinearRegression()

In [25]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [26]:
lr.score(x_train,y_train)

0.5808525092365294

In [27]:
y_pred=lr.predict(x_test)

In [28]:
y_pred

array([[217502.31197409],
       [289859.83693386],
       [205500.92911864],
       ...,
       [124448.81206781],
       [263670.8478699 ],
       [219495.71037656]])

In [35]:
x_train.shape

(16512, 8)

In [36]:
y_train.shape

(16512, 1)

In [ ]:
#FOR MULTIPLEAR LINEAR REGRESSION PREDICTION ACCURACY IS 58%.IT'S NOT TOO GOOD PREDICTION